# Site settings
title: "Yu Zhang - Homepage"
description: "Personal homepage"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "images/avatar-5.jpg"
resume_name:                    "Yu Zhang (张宇)"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yucrazing@mail.bnu.edu.cn"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "#"
resume_contact_address:         "Beijing Normal University"

resume_header_contact_info:     "<font size=2>yucrazing@mail.bnu.edu.cn</font>"
display_header_contact_info:    "true"

resume_header_intro: "<p >
                            I am a research assistant in <a href=\"https://yangzzzy.github.io/\">Prof. Yin Yang</a> 's lab at the University of Utah. Meanwhile, I am also collaborating with <a href=\"https://people.csail.mit.edu/ganchuang/\">Prof. Chuang Gan</a>, participating in the <a href=\"https://genesis-embodied-ai.github.io/\">Genesis</a> project.
                            <br>
                            <br>
                            Before joining Yin Yang's lab, I worked at MeshyAI (working with <a href=\"https://tiantianliu.cn/\">Dr. Tiantian Liu</a> and <a href=\"https://yuanming.taichi.graphics/\">Dr. Yuanming Hu</a>) and Tencent Games, and interned at NetEase Games.
                            I earned both my bachelor's and master's degrees in Computer Science and Technology from Beijing Normal University, where I was advised by Prof. Zhongke Wu.
                            <br>
                            <br>
                            My research interests include <strong>3D AIGC</strong>, <strong>Computer Graphics (especially physical simulation)</strong> and <strong>Robotics</strong> etc.
                            <br>
                            <br>
                            <strong> I'm actively looking for PhD positions in fall 2025. Please contact me if you're interested! </strong>
                        </p>
                        <a href=\"https://yucrazing.github.io/assets/files/YuZhang_CV_en.pdf\"> CV </a>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank

#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       false
resume_section_experience:      true
resume_section_publications:    true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false
resume_section_applications:    false
resume_section_gallery:         true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/YuCrazing/"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
#  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://yucrazing.github.io/resume/"
#  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
